### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by walkerbryan** [Checkmarx/ast-github-action#103]
### Describe the bug
When trying to kick off a Checkmarx scan via Github, we're receiving an error in the Checkmarx AST CLI Action step that causes the action to fail.

### Expected behavior
The Github action runs successfully and kicks off a scan in Checkmarx.

### Actual behavior
The Github action is failing before a scan in Checkmarx can be initiated.  This first happened on our weekly scheduled scan on 1/21, then has happened on each subsequent try when attempting to re-run failed jobs manually.  

### Steps to reproduce
1. Go to our organization's private repo
2. Click on Actions
3. Click on the fail Checkmarx SAST workflow 
4. Select Re-run failed jobs
5. Job runs for 10-30 seconds and then fails on Checkmarx AST CLI Action

### Logs
Run checkmarx/ast-github-action@main
  with:
    project_name: tyler-technologies/eagle-cm-frontend
    cx_tenant: tylertech
    base_uri: https://ast.checkmarx.net
    additional_params: --apikey ***
    branch: refs/heads/develop
    github_token: ***
    repo_name: eagle-cm-frontend
    namespace: tyler-technologies
/usr/bin/docker run --name c7fce1cf58a0b4e14a[2](https://github.com/tyler-technologies/eagle-cm-frontend/actions/runs/3974116219/jobs/6861760142#step:4:2)afbf49122c[3](https://github.com/tyler-technologies/eagle-cm-frontend/actions/runs/3974116219/jobs/6861760142#step:4:3)f0b_20[4](https://github.com/tyler-technologies/eagle-cm-frontend/actions/runs/3974116219/jobs/6861760142#step:4:4)624 --label 498[5](https://github.com/tyler-technologies/eagle-cm-frontend/actions/runs/3974116219/jobs/6861760142#step:4:5)9c --workdir /github/workspace --rm -e "INPUT_PROJECT_NAME" -e "INPUT_CX_TENANT" -e "INPUT_BASE_URI" -e "INPUT_ADDITIONAL_PARAMS" -e "INPUT_CX_CLIENT_ID" -e "INPUT_CX_CLIENT_SECRET" -e "INPUT_BRANCH" -e "INPUT_GITHUB_TOKEN" -e "INPUT_REPO_NAME" -e "INPUT_NAMESPACE" -e "INPUT_PR_NUMBER" -e "CX_BASE_URI" -e "CX_TENANT" -e "CX_CLIENT_ID" -e "CX_CLIENT_SECRET" -e "GITHUB_TOKEN" -e "BRANCH" -e "PROJECT_NAME" -e "ADDITIONAL_PARAMS" -e "REPO_NAME" -e "NAMESPACE" -e "PR_NUMBER" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true --entrypoint "/app/entrypoint.sh" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/eagle-cm-frontend/eagle-cm-frontend":"/github/workspace" 49859c:7fce1cf58a0b4e14a2afbf49122c3f0b  "https://ast.checkmarx.net/" "tylertech" "" "" "***" "tyler-technologies/eagle-cm-frontend" "--apikey ***" "eagle-cm-frontend" "tyler-technologies" ""
Creating directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2[6](https://github.com/tyler-technologies/eagle-cm-frontend/actions/runs/3974116219/jobs/6861760142#step:4:6)8 pc=0x8038[7](https://github.com/tyler-technologies/eagle-cm-frontend/actions/runs/3974116219/jobs/6861760142#step:4:7)5]

goroutine 1 [running]:
github.com/checkmarx/ast-cli/internal/wrappers.(*JWTStruct).GetAllowedEngines(0x1[8](https://github.com/tyler-technologies/eagle-cm-frontend/actions/runs/3974116219/jobs/6861760142#step:4:8))
	/Users/runner/work/ast-cli/ast-cli/internal/wrappers/jwt-helper.go:[9](https://github.com/tyler-technologies/eagle-cm-frontend/actions/runs/3974116219/jobs/6861760142#step:4:9)1 +0x35
github.com/checkmarx/ast-cli/internal/commands.validateScanTypes(0xc00013b820?, {0xa28180?, 0xc0000cee00?})
	/Users/runner/work/ast-cli/ast-cli/internal/commands/scan.go:821 +0x4a
github.com/checkmarx/ast-cli/internal/commands.createScanModel(0x0?, {0xa28260, 0xc00017c8[10](https://github.com/tyler-technologies/eagle-cm-frontend/actions/runs/3974116219/jobs/6861760142#step:4:10)}, {0xa2e180, 0xc00017c820}, {0xa28160, 0xc00017c7f0}, {0xa2e1d0, 0xc0000c8d40}, {0xa28180, ...})
	/Users/runner/work/ast-cli/ast-cli/internal/commands/scan.go:1381 +0x86
github.com/checkmarx/ast-cli/internal/commands.runCreateScanCommand.func1(0xc000[12](https://github.com/tyler-technologies/eagle-cm-frontend/actions/runs/3974116219/jobs/6861760142#step:4:13)4600?, {0xc00021a180?, 0x0?, 0xc?})
	/Users/runner/work/ast-cli/ast-cli/internal/commands/scan.go:1299 +0x18e
github.com/spf[13](https://github.com/tyler-technologies/eagle-cm-frontend/actions/runs/3974116219/jobs/6861760142#step:4:14)/cobra.(*Command).execute(0xc000124600, {0xc00021a0c0, 0xc, 0xc})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:9[16](https://github.com/tyler-technologies/eagle-cm-frontend/actions/runs/3974116219/jobs/6861760142#step:4:17) +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001[24](https://github.com/tyler-technologies/eagle-cm-frontend/actions/runs/3974116219/jobs/6861760142#step:4:25)000)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/Users/runner/work/ast-cli/ast-cli/cmd/main.go:87 +0x945
PR decoration not created.

![yml file](https://user-images.githubusercontent.com/114257376/214878932-40af0cc8-40a9-4faf-a7e2-8f9556bcbb6f.jpg)

**Comment by pedrompflopes** [comment]
Hi @walkerbryan  

Can you please generate a new API key and use it ? 

We will try to reproduce the case locally. 

Thanks,

**Comment by walkerbryan** [comment]
@pedrompflopes I generated a new API key in Checkmarx and updated our secret in the CX_API_KEY in the affected repo, but the action again failed with the same error.

**Comment by pedrompflopes** [comment]
@walkerbryan  Please try again.

**Comment by walkerbryan** [comment]
@pedrompflopes action failed, but different message in logs:

Run checkmarx/ast-github-action@main
  with:
    project_name: tyler-technologies/eagle-cm-frontend
    cx_tenant: tylertech
    base_uri: https://ast.checkmarx.net
    additional_params: --apikey ***
    branch: refs/heads/develop
    github_token: ***
    repo_name: eagle-cm-frontend
    namespace: tyler-technologies
/usr/bin/docker run --name ce98cd4d98183411f86[2](https://github.com/tyler-technologies/eagle-cm-frontend/actions/runs/4017193506/jobs/6922268067#step:4:2)e8ff7a56eec08_1ab[3](https://github.com/tyler-technologies/eagle-cm-frontend/actions/runs/4017193506/jobs/6922268067#step:4:3)79 --label [4](https://github.com/tyler-technologies/eagle-cm-frontend/actions/runs/4017193506/jobs/6922268067#step:4:4)98[5](https://github.com/tyler-technologies/eagle-cm-frontend/actions/runs/4017193506/jobs/6922268067#step:4:5)9c --workdir /github/workspace --rm -e "INPUT_PROJECT_NAME" -e "INPUT_CX_TENANT" -e "INPUT_BASE_URI" -e "INPUT_ADDITIONAL_PARAMS" -e "INPUT_CX_CLIENT_ID" -e "INPUT_CX_CLIENT_SECRET" -e "INPUT_BRANCH" -e "INPUT_GITHUB_TOKEN" -e "INPUT_REPO_NAME" -e "INPUT_NAMESPACE" -e "INPUT_PR_NUMBER" -e "CX_BASE_URI" -e "CX_TENANT" -e "CX_CLIENT_ID" -e "CX_CLIENT_SECRET" -e "GITHUB_TOKEN" -e "BRANCH" -e "PROJECT_NAME" -e "ADDITIONAL_PARAMS" -e "REPO_NAME" -e "NAMESPACE" -e "PR_NUMBER" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true --entrypoint "/app/entrypoint.sh" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/eagle-cm-frontend/eagle-cm-frontend":"/github/workspace" 49859c:e98cd4d98183411f862e8ff7a56eec08  "https://ast.checkmarx.net/" "tylertech" "" "" "***" "tyler-technologies/eagle-cm-frontend" "--apikey ***" "eagle-cm-frontend" "tyler-technologies" ""
Creating directory
**Error validating scan types: Token decoding error: json: cannot unmarshal string into Go struct field JWTStruct.aud of type []string**
PR decoration not created.

**Comment by pedrompflopes** [comment]
@walkerbryan  Please try again with the new version. 

Thanks

**Comment by walkerbryan** [comment]
@pedrompflopes Everything is running again without issue.  Thank you for your assistance.
