### ISSUE TITLE
[BUG] wrong workflow summary for async scans

### ISSUE THREAD

**Issue by ArnaudLacroix** [Checkmarx/ast-github-action#133]
### Describe the bug
Results summary shows 0 vulnerability for async scans

### Expected behavior
If a scan is launched in async mode, there shouldn't be any summary generated by the action (as the scan results is not available at that time)

### Actual behavior
When a scan is launched in async mode, the action summary is generated with 0 vulnerability.

### Steps to reproduce
Call the GitHub action with --async additional parameter

**Comment by pedrompflopes** [comment]
Hi @ArnaudLacroix 

Thanks for raising this. It is resolved in the last release. 

Thanks.
