### ISSUE TITLE
[REQ] Action input to run scans asynchronously

### ISSUE THREAD

**Issue by jimmy-lt** [Checkmarx/ast-github-action#149]
### Issue

Running an asynchronous scan is a common action, however, the only way to trigger an asynchronous scan is by providing an additional argument via the `additional_params` input. This is not very user friendly.

### Proposed solution

Provide a dedicated action input to run scans asynchronously.

**Comment by pedrompflopes** [comment]
Hi @jimmy-lt 
Thanks for the request, but currently we are not planning to add these options outside of the additional parameters.

Thanks.
