### ISSUE TITLE
[REQ] Action input to set project groups

### ISSUE THREAD

**Issue by jimmy-lt** [Checkmarx/ast-github-action#150]
### Issue

Assigning groups to a project is a common action, however, the only way to do this is by providing an additional argument via the `additional_params` input. This is not very user friendly.

### Proposed solution

Provide a dedicated action input to assign groups to projects.

**Comment by pedrompflopes** [comment]
Hi @jimmy-lt 
Thanks for the request, but currently we are not planning to add these options outside of the additional parameters.

Thanks.
