### ISSUE TITLE
[REQ] Job summary

### ISSUE THREAD

**Issue by iamludal** [Checkmarx/ast-github-action#62]
### Is your request related to a workflow problem?

When a scan fails, one should manually open Checkmarx, search for the project, search for the scan... It would be much easier if, instead, the job summary would be filled with a URL to the corresponding scan.

### Propose a solution

GitHub Actions Jobs can now be decorated with a summary: [Supercharging GitHub Actions with Job Summaries](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/). A link to the scan could be added, even if it is a success, to quickly access the report.

Later on, why not also add the report details to the job summary, the same way as how it is shown in the stdout.

### Additional comments

The most important thing here is the link to the corresponding scan. The report details is a "nice to have".

**Comment by pedrompflopes** [comment]
@iamludal  Thanks for your suggestion. We will check with our product team and prioritize it. 

@jbrotsos  @Yoavast

**Comment by pedrompflopes** [comment]
@iamludal  Thanks for your contribution. We included part of your PR in the current release. We found out that if you make the BASE_URI a secret, then the value is masked and the link won't work. 

We will try to find a solution and add it in the next releases.
