### ISSUE TITLE
[REQ] Use of deprecated API

### ISSUE THREAD

**Issue by farhan-ejaz** [Checkmarx/ast-github-action#90]
Version 2.0.12 reports use of deprecated API. 

![image](https://user-images.githubusercontent.com/19402644/204442436-fc45810c-25ee-4319-b590-ccadacf9c699.png)

**Comment by pedrompflopes** [comment]
@farhan-ejaz  Thanks for raising this. We will add this to our roadmap.

**Comment by cmotsn** [comment]
Hello! Is this something that can be done by an external contributor like me? We'd like to get rid of deprecated warnings on our workflows.

**Comment by pedrompflopes** [comment]
Hi @cmotsn 

The issue was on our roadmap and it is now fixed #98 . Thanks for raising it and for being willing to support us with a fix. 


[Version 2.0.14](https://github.com/Checkmarx/ast-github-action/releases/tag/2.0.14)

Thanks

**Comment by cmotsn** [comment]
Thank you!
(You probably know but just in case, there are [still](https://github.com/Checkmarx/ast-github-action/blob/e216d56a6535d1921fae7e88d50dd580892ed3ef/.github/workflows/release.yml#L31) [uses](https://github.com/Checkmarx/ast-github-action/blob/e216d56a6535d1921fae7e88d50dd580892ed3ef/.github/workflows/release.yml#L43) of `set-ouput` in the action publishing workflow, but they should not affect users of the action.)
